### ISSUE TITLE
No Javascript functionality on the docs?

### ISSUE THREAD

**Issue by PhillippOhlandt** [jgthms/bulma-website#10]
Seems like the closing buttons on tags and notifications doesn't work.
http://bulma.io/documentation/elements/notifications/

Also the Burger Menu on the header component in mobile view doesn't work in the docs
http://bulma.io/documentation/layout/header/

**Comment by jgthms** [comment]
Ah yeah, there's no JS functionality in Bulma itself, only on the website. Some people are working on JS plugins...

**Comment by PhillippOhlandt** [comment]
Oh, uhm ... ok, it's not a big deal to make that work with vuejs components.

**Comment by JustSteveKing** [comment]
+1 @PhillippOhlandt
