### ISSUE TITLE
`.header` is either deprecated, or missing documentation?

### ISSUE THREAD

**Issue by vdh** [jgthms/bulma-website#46]
The Container documentation is the only place I can find that mentions `.header`.

I tried a wild guess and managed to find http://bulma.io/documentation/layout/header/
but this page is not linked to from the Layout documentation's tabs (Container, Hero, Section, Footer).

So is `.header` deprecated, or is it just missing from the docs?

**Comment by jgthms** [comment]
Ah yes it's deprecated. This file and page are still there but I'll remove them. Thanks.
