### ISSUE TITLE
Documentation - layout issue on `elements -> messages`

### ISSUE THREAD

**Issue by adambair** [jgthms/bulma-website#5]
Layout issue on `elements -> messages`

![](http://cl.ly/1h2U0G420q0w/Image%202016-01-29%20at%207.07.13%20PM.png)

http://bulma.io/documentation/elements/messages/

**Comment by jgthms** [comment]
@adambair can you check if this is fixed? I couldn't reproduce the bug but I think I know where it was coming from.

**Comment by adambair** [comment]
Fixed.
![](http://cl.ly/42350J3u2x1P/Image%202016-02-01%20at%209.46.31%20AM.png)
